defmodule CunweiWong.Render do
  @moduledoc false

  use Phoenix.Component
  alias CunweiWong.Content
  import Phoenix.HTML

  def format_post_date(date) do
    Calendar.strftime(date, "%Y年%m月%d日")
  end

  def post(assigns) do
    ~H"""
    <.layout
      title={"#{@title} — #{Content.site_title()}"}
      route={@route}
      date={@date}
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 mb-4"><%= @title %></h1>
        <div class="flex items-center text-sm text-gray-500 dark:text-gray-400 flex-wrap gap-y-2">
          <span class="mr-2 hidden sm:inline">✍️ wangcw</span>
          <span class="hidden sm:inline">&bull;</span>
          <span class="sm:ml-2">📅 <%= format_post_date(@date) %></span>
          <%= if @categories && is_list(@categories) do %>
            <span class="hidden sm:inline ml-2">&bull;</span>
            <div class="flex gap-2 ml-2">
              <%= for cat <- @categories do %>
                <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                  🏷️ <%= cat %>
                </span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      
      <article class="prose prose-zinc dark:prose-invert max-w-none">
        <%= raw @body %>
      </article>
      
      <div class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 flex justify-between items-center text-sm text-gray-500 dark:text-gray-400">
        <div>发布于: <%= format_post_date(@date) %></div>
        <button onclick="window.scrollTo({top: 0, behavior: 'smooth'});" class="hover:text-gray-900 dark:hover:text-gray-100 transition cursor-pointer">
          返回顶部 &uarr;
        </button>
      </div>
      <footer class="mt-12 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.querySelectorAll('code').forEach(function(el) {
          el.contentEditable = true
        });
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def index(assigns) do
    grouped_posts =
      assigns.posts
      |> Enum.group_by(& &1.date)
      |> Enum.sort_by(fn {date, _posts} -> date end, {:desc, Date})

    assigns = Map.put(assigns, :grouped_posts, grouped_posts)

    ~H"""
    <.layout
      title={Content.site_title()}
      route="/"
    >
      <div class="space-y-12">
        <%= for {date, posts} <- @grouped_posts do %>
          <section>
            <h2 class="text-xl font-bold mb-4 text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-800 pb-2"><%= format_post_date(date) %></h2>
            <div class="grid gap-6">
              <%= for post <- posts do %>
                <a href={post.route} class="group block p-6 bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300 ring-1 ring-gray-900/5 dark:ring-white/5 flex flex-col gap-2">
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors"><%= post.title %></h3>
                  <%= if post.categories && is_list(post.categories) do %>
                    <div class="flex flex-wrap gap-2 mt-1">
                      <%= for cat <- post.categories do %>
                        <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                          🏷️ <%= cat %>
                        </span>
                      <% end %>
                    </div>
                  <% end %>
                </a>
              <% end %>
            </div>
          </section>
        <% end %>
      </div>
      <div class="mt-12 text-center">
        <a href="/archive/" class="inline-flex items-center text-sm font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 transition mb-4">
          阅读更多文章 &rarr;
        </a>
      </div>
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def archive(assigns) do
    grouped_posts =
      assigns.posts
      |> Enum.group_by(& &1.date)
      |> Enum.sort_by(fn {date, _posts} -> date end, {:desc, Date})

    assigns = Map.put(assigns, :grouped_posts, grouped_posts)

    ~H"""
    <.layout
      title={Content.site_title()}
      route="/"
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100">归档</h1>
      </div>
      <div class="space-y-12">
        <%= for {date, posts} <- @grouped_posts do %>
          <section>
            <h2 class="text-xl font-bold mb-4 text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-800 pb-2"><%= format_post_date(date) %></h2>
            <div class="grid gap-6">
              <%= for post <- posts do %>
                <a href={post.route} class="group block p-6 bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300 ring-1 ring-gray-900/5 dark:ring-white/5 flex flex-col gap-2">
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors"><%= post.title %></h3>
                  <%= if post.categories && is_list(post.categories) do %>
                    <div class="flex flex-wrap gap-2 mt-1">
                      <%= for cat <- post.categories do %>
                        <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                          🏷️ <%= cat %>
                        </span>
                      <% end %>
                    </div>
                  <% end %>
                </a>
              <% end %>
            </div>
          </section>
        <% end %>
      </div>
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def routes(assigns) do
    ~H"""
    <.layout
      title={Content.site_title()}
      route="/routes/"
    >
      <style>
        .amap-logo, .amap-copyright { display: none !important; }
      </style>
      <div class="route-page group bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm ring-1 ring-gray-900/5 dark:ring-white/5" id="route-app" data-endpoint="/api/locations">
        <div class="route-header mb-6">
          <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 mb-4">轨迹</h1>
          <p class="text-gray-600 dark:text-gray-400">展示某一天的定位点轨迹，地图底图来自高德地图（马卡龙主题）。</p>
          <p class="route-tip mt-2 text-sm text-gray-500 dark:text-gray-500" id="route-tip">请输入日期后加载定位数据。</p>
        </div>
        <div class="route-controls">
          <label for="route-date" class="text-gray-700 dark:text-gray-300 font-medium whitespace-nowrap">日期</label>
          <input type="date" id="route-date" />
          <button id="route-load">加载</button>
          <span class="route-status" id="route-status"></span>
        </div>
        <div class="route-stats">
          <div class="route-stat">
            <span class="route-stat-label">点数</span>
            <span class="route-stat-value" id="route-count">-</span>
          </div>
          <div class="route-stat">
            <span class="route-stat-label">时间范围</span>
            <span class="route-stat-value" id="route-range">-</span>
          </div>
        </div>
        <div id="route-map" class="route-map"></div>
      </div>
      <footer class="mt-16 pt-8 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <!-- 引入高德地图 API，注意替换为您自己的 KEY 和安全密钥 -->
      <script>
        window._AMapSecurityConfig = {
            securityJsCode: 'YOUR_AMAP_SECURITY_CODE', // TODO: 请替换为您的安全密钥
        }
      </script>
      <script src="https://webapi.amap.com/maps?v=2.0&key=YOUR_AMAP_KEY"></script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
      <script>
        // === WGS84 转 GCJ02 的纯 JS 算法 ===
        const PI = 3.1415926535897932384626;
        const a = 6378245.0;
        const ee = 0.00669342162296594323;
        function transformLat(x, y) {
          let ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * Math.sqrt(Math.abs(x));
          ret += (20.0 * Math.sin(6.0 * x * PI) + 20.0 * Math.sin(2.0 * x * PI)) * 2.0 / 3.0;
          ret += (20.0 * Math.sin(y * PI) + 40.0 * Math.sin(y / 3.0 * PI)) * 2.0 / 3.0;
          ret += (160.0 * Math.sin(y / 12.0 * PI) + 320 * Math.sin(y * PI / 30.0)) * 2.0 / 3.0;
          return ret;
        }
        function transformLon(x, y) {
          let ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * Math.sqrt(Math.abs(x));
          ret += (20.0 * Math.sin(6.0 * x * PI) + 20.0 * Math.sin(2.0 * x * PI)) * 2.0 / 3.0;
          ret += (20.0 * Math.sin(x * PI) + 40.0 * Math.sin(x / 3.0 * PI)) * 2.0 / 3.0;
          ret += (150.0 * Math.sin(x / 12.0 * PI) + 300.0 * Math.sin(x / 30.0 * PI)) * 2.0 / 3.0;
          return ret;
        }
        function outOfChina(lng, lat) {
          return lng < 72.004 || lng > 137.8347 || lat < 0.8293 || lat > 55.8271;
        }
        function wgs84ToGcj02(lng, lat) {
          if (outOfChina(lng, lat)) return [lng, lat];
          let dLat = transformLat(lng - 105.0, lat - 35.0);
          let dLng = transformLon(lng - 105.0, lat - 35.0);
          let radLat = lat / 180.0 * PI;
          let magic = Math.sin(radLat);
          magic = 1 - ee * magic * magic;
          let sqrtMagic = Math.sqrt(magic);
          dLat = (dLat * 180.0) / ((a * (1 - ee)) / (magic * sqrtMagic) * PI);
          dLng = (dLng * 180.0) / (a / sqrtMagic * Math.cos(radLat) * PI);
          return [lng + dLng, lat + dLat];
        }

        // === 轨迹业务代码 ===
        const routeApp = document.getElementById('route-app');
        const dateInput = document.getElementById('route-date');
        const loadButton = document.getElementById('route-load');
        const statusEl = document.getElementById('route-status');
        const countEl = document.getElementById('route-count');
        const rangeEl = document.getElementById('route-range');
        const endpoint = routeApp.dataset.endpoint || '';
        let map;
        let trackLayer;
        let startMarker;
        let endMarker;

        const now = new Date();
        const localDate = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
          .toISOString()
          .slice(0, 10);

        const params = new URLSearchParams(window.location.search);
        const initialDate = params.get('date') || localDate;
        dateInput.value = initialDate;

        function setStatus(text, tone) {
          statusEl.textContent = text || '';
          statusEl.dataset.tone = tone || '';
        }

        function setTip(text, tone) {
          const tipEl = document.getElementById('route-tip');
          if (!tipEl) return;
          tipEl.textContent = text || '';
          tipEl.dataset.tone = tone || '';
        }

        function formatTime(value) {
          if (!value) return '';
          const date = new Date(value);
          if (Number.isNaN(date.getTime())) return '';
          const pad = (num) => String(num).padStart(2, '0');
          return `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
        }

        function normalizePoints(data) {
          if (Array.isArray(data)) return data;
          if (data && Array.isArray(data.points)) return data.points;
          return [];
        }

        function toGcj02LngLat(point) {
          const lat = point.lat ?? point.latitude;
          const lng = point.lng ?? point.lon ?? point.longitude;
          const latNumber = Number(lat);
          const lngNumber = Number(lng);
          if (!Number.isFinite(latNumber) || !Number.isFinite(lngNumber)) return null;
          // 转换为 GCJ02 火星坐标以便在高德地图上准确显示
          return wgs84ToGcj02(lngNumber, latNumber);
        }

        function ensureMap(center) {
          if (!map && typeof AMap !== 'undefined') {
            map = new AMap.Map('route-map', {
              zoom: 12,
              center: center,
              mapStyle: 'amap://styles/macaron',
              showLabel: true
            });
          } else if (map) {
            map.setCenter(center);
          }
        }

        function renderTrack(points) {
          // 过滤并转换坐标系为火星坐标 (GCJ02)
          const lnglats = points
            .map(toGcj02LngLat)
            .filter((item) => item);

          if (lnglats.length === 0) {
            setStatus('没有可用的定位点', 'empty');
            setTip('该日期没有可用数据。', 'empty');
            countEl.textContent = '0';
            rangeEl.textContent = '-';
            return;
          }

          ensureMap(lnglats[0]);

          if (trackLayer) map.remove(trackLayer);
          if (startMarker) map.remove(startMarker);
          if (endMarker) map.remove(endMarker);

          trackLayer = new AMap.Polyline({
            path: lnglats,
            strokeColor: '#2f4bff',
            strokeWeight: 4,
            strokeOpacity: 0.8,
            lineJoin: 'round',
            lineCap: 'round',
            zIndex: 50
          });
          map.add(trackLayer);

          startMarker = new AMap.CircleMarker({
            center: lnglats[0],
            radius: 5,
            fillColor: '#10b981',
            strokeColor: '#ffffff',
            strokeWeight: 2,
            zIndex: 100
          });
          map.add(startMarker);
          
          endMarker = new AMap.CircleMarker({
            center: lnglats[lnglats.length - 1],
            radius: 5,
            fillColor: '#ef4444',
            strokeColor: '#ffffff',
            strokeWeight: 2,
            zIndex: 100
          });
          map.add(endMarker);

          // 自动缩放地图视口以包含整个轨迹
          map.setFitView([trackLayer]);

          countEl.textContent = String(lnglats.length);
          const startTime = formatTime(points[0]?.ts || points[0]?.time || points[0]?.timestamp);
          const endTime = formatTime(points[points.length - 1]?.ts || points[points.length - 1]?.time || points[points.length - 1]?.timestamp);
          rangeEl.textContent = startTime && endTime ? `${startTime} - ${endTime}` : '-';
          setStatus('加载成功', 'success');
          setTip('数据来自后端接口。', 'success');
        }

        async function fetchPoints(date) {
          if (!endpoint) {
            throw new Error('missing-endpoint');
          }
          const response = await fetch(`${endpoint}?date=${date}`);
          if (!response.ok) {
            throw new Error(`status:${response.status}`);
          }
          return response.json();
        }

        async function loadDate(date) {
          if (!date) return;
          setStatus('加载中...', 'loading');
          setTip('正在从后端获取数据...', 'loading');
          try {
            const data = await fetchPoints(date);
            renderTrack(normalizePoints(data));
          } catch (error) {
            setStatus('加载失败', 'error');
            setTip('接口不可用或数据为空，请稍后重试。', 'error');
            countEl.textContent = '-';
            rangeEl.textContent = '-';
          }
        }

        loadButton.addEventListener('click', function() {
          const date = dateInput.value;
          const url = new URL(window.location.href);
          url.searchParams.set('date', date);
          window.history.replaceState({}, '', url.toString());
          loadDate(date);
        });

        dateInput.addEventListener('change', function() {
          loadButton.click();
        });

        if (!endpoint) {
          setStatus('接口未配置', 'error');
          setTip('当前未配置后端接口，无法加载定位数据。', 'error');
        } else {
          loadDate(initialDate);
        }
      </script>
    </.layout>
    """
  end

  def page(assigns) do
    ~H"""
    <.layout
      title={"#{@title} — #{Content.site_title()}"}
      route={@route}
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100"><%= @title %></h1>
      </div>
      
      <article class="prose prose-zinc dark:prose-invert max-w-none">
        <%= raw @body %>
      </article>
      
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def layout(assigns) do
    ~H"""
    <!DOCTYPE html>
    <html lang="zh-CN" class="scroll-smooth">
      <head>
        <meta charset="utf-8" />
        <title><%= @title %></title>
        <meta name="author" content={Content.site_author()} />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="ROBOTS" content="INDEX, FOLLOW" />
        <meta property="og:title" content={@title} />
        <meta property="og:url" content={"#{Content.site_url()}#{@route}"}>
        <meta name="color-scheme" content="light dark" />
        <link rel="stylesheet" href="/assets/app.css" />
      </head>
      <body class="bg-gray-50 text-gray-900 dark:bg-[#0f172a] dark:text-gray-100 min-h-screen antialiased flex flex-col">
        <header class="sticky top-0 z-50 w-full backdrop-blur transition-colors duration-500 bg-white/75 dark:bg-[#0f172a]/75 border-b border-gray-200 dark:border-gray-800">
          <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
              <div class="flex-shrink-0">
                <a href="/" class="font-bold text-xl tracking-tight text-indigo-600 dark:text-indigo-400 font-serif italic">wangcw</a>
              </div>
              <nav class="flex space-x-6 text-sm font-medium text-gray-700 dark:text-gray-300">
                <a href="/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">主页</a>
                <a href="/archive/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">归档</a>
                <a href="/routes/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">轨迹</a>
                <a href="/about/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">关于</a>
              </nav>
            </div>
          </div>
        </header>
        <main class="flex-grow max-w-3xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <%= render_slot(@inner_block) %>
        </main>
      </body>
    </html>
    """
  end

  def redirect(assigns) do
    ~H"""
    <!DOCTYPE html>
    <html lang="en-us">
      <head>
        <title><%= @target%></title>
        <link rel="canonical" href={@target}>
        <meta name="robots" content="noindex">
        <meta charset="utf-8">
        <meta http-equiv="refresh" content={"0; url=#{@target}"}>
      </head>
    </html>
    """
  end
end
