defmodule CunweiWong.Render do
  @moduledoc false

  use Phoenix.Component
  alias CunweiWong.Content
  import Phoenix.HTML

  def format_post_date(date) do
    Calendar.strftime(date, "%Y年%m月%d日")
  end

  def post(assigns) do
    ~H"""
    <.layout
      title={"#{@title} — #{Content.site_title()}"}
      route={@route}
      date={@date}
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 mb-4"><%= @title %></h1>
        <div class="flex items-center text-sm text-gray-500 dark:text-gray-400 flex-wrap gap-y-2">
          <span class="mr-2 hidden sm:inline">✍️ wangcw</span>
          <span class="hidden sm:inline">&bull;</span>
          <span class="sm:ml-2">📅 <%= format_post_date(@date) %></span>
          <%= if @categories && is_list(@categories) do %>
            <span class="hidden sm:inline ml-2">&bull;</span>
            <div class="flex gap-2 ml-2">
              <%= for cat <- @categories do %>
                <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                  🏷️ <%= cat %>
                </span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      
      <article class="prose prose-zinc dark:prose-invert max-w-none">
        <%= raw @body %>
      </article>
      
      <div class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 flex justify-between items-center text-sm text-gray-500 dark:text-gray-400">
        <div>发布于: <%= format_post_date(@date) %></div>
        <button onclick="window.scrollTo({top: 0, behavior: 'smooth'});" class="hover:text-gray-900 dark:hover:text-gray-100 transition cursor-pointer">
          返回顶部 &uarr;
        </button>
      </div>
      <footer class="mt-12 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.querySelectorAll('code').forEach(function(el) {
          el.contentEditable = true
        });
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def index(assigns) do
    grouped_posts =
      assigns.posts
      |> Enum.group_by(& &1.date)
      |> Enum.sort_by(fn {date, _posts} -> date end, {:desc, Date})

    assigns = Map.put(assigns, :grouped_posts, grouped_posts)

    ~H"""
    <.layout
      title={Content.site_title()}
      route="/"
    >
      <div class="space-y-12">
        <%= for {date, posts} <- @grouped_posts do %>
          <section>
            <h2 class="text-xl font-bold mb-4 text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-800 pb-2"><%= format_post_date(date) %></h2>
            <div class="grid gap-6">
              <%= for post <- posts do %>
                <a href={post.route} class="group block p-6 bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300 ring-1 ring-gray-900/5 dark:ring-white/5 flex flex-col gap-2">
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors"><%= post.title %></h3>
                  <%= if post.categories && is_list(post.categories) do %>
                    <div class="flex flex-wrap gap-2 mt-1">
                      <%= for cat <- post.categories do %>
                        <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                          🏷️ <%= cat %>
                        </span>
                      <% end %>
                    </div>
                  <% end %>
                </a>
              <% end %>
            </div>
          </section>
        <% end %>
      </div>
      <div class="mt-12 text-center">
        <a href="/archive/" class="inline-flex items-center text-sm font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 transition mb-4">
          阅读更多文章 &rarr;
        </a>
      </div>
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def archive(assigns) do
    grouped_posts =
      assigns.posts
      |> Enum.group_by(& &1.date)
      |> Enum.sort_by(fn {date, _posts} -> date end, {:desc, Date})

    assigns = Map.put(assigns, :grouped_posts, grouped_posts)

    ~H"""
    <.layout
      title={Content.site_title()}
      route="/"
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100">归档</h1>
      </div>
      <div class="space-y-12">
        <%= for {date, posts} <- @grouped_posts do %>
          <section>
            <h2 class="text-xl font-bold mb-4 text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-800 pb-2"><%= format_post_date(date) %></h2>
            <div class="grid gap-6">
              <%= for post <- posts do %>
                <a href={post.route} class="group block p-6 bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300 ring-1 ring-gray-900/5 dark:ring-white/5 flex flex-col gap-2">
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors"><%= post.title %></h3>
                  <%= if post.categories && is_list(post.categories) do %>
                    <div class="flex flex-wrap gap-2 mt-1">
                      <%= for cat <- post.categories do %>
                        <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10 dark:bg-indigo-900/40 dark:text-indigo-300 dark:ring-indigo-700/30">
                          🏷️ <%= cat %>
                        </span>
                      <% end %>
                    </div>
                  <% end %>
                </a>
              <% end %>
            </div>
          </section>
        <% end %>
      </div>
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def routes(assigns) do
    ~H"""
    <.routes_layout title={Content.site_title()} route="/routes/" />
    """
  end

  def routes_layout(assigns) do
    ~H"""
    <!DOCTYPE html>
    <html lang="zh-CN">
      <head>
        <meta charset="utf-8" />
        <title><%= @title %></title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light dark" />
        <link rel="stylesheet" href="/vendor/leaflet.css" />
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          html, body { height: 100%; width: 100%; overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
          #route-map { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; }
          .route-panel {
            position: absolute;
            top: 10px;
            right: 10px;
            z-index: 1000;
            background: rgba(255, 255, 255, 0.75);
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border-radius: 12px;
            padding: 10px 14px;
            display: flex;
            align-items: center;
            gap: 8px;
            box-shadow: 0 2px 12px rgba(0,0,0,0.12);
            border: 1px solid rgba(255,255,255,0.3);
          }
          @media (prefers-color-scheme: dark) {
            .route-panel {
              background: rgba(15, 23, 42, 0.7);
              border-color: rgba(255,255,255,0.08);
              box-shadow: 0 2px 12px rgba(0,0,0,0.4);
            }
          }
          .route-panel input[type="date"] {
            padding: 5px 10px;
            border: 1px solid rgba(0,0,0,0.12);
            border-radius: 8px;
            background: rgba(255,255,255,0.6);
            font-size: 14px;
            color: #1e293b;
            outline: none;
            cursor: pointer;
            transition: border-color 0.2s;
          }
          .route-panel input[type="date"]:focus { border-color: #6366f1; }
          @media (prefers-color-scheme: dark) {
            .route-panel input[type="date"] {
              background: rgba(30, 41, 59, 0.7);
              border-color: rgba(255,255,255,0.1);
              color: #e2e8f0;
            }
          }
          .route-panel .route-status {
            font-size: 12px;
            color: #64748b;
            white-space: nowrap;
          }
          .route-panel .route-status[data-tone="loading"] { color: #f59e0b; }
          .route-panel .route-status[data-tone="success"] { color: #10b981; }
          .route-panel .route-status[data-tone="error"] { color: #ef4444; }
          .route-panel .route-info {
            font-size: 11px;
            color: #94a3b8;
            display: flex;
            gap: 10px;
          }
          @media (prefers-color-scheme: dark) {
            .route-panel .route-status { color: #94a3b8; }
          }
          .route-nav {
            position: absolute;
            top: 10px;
            left: 10px;
            z-index: 1000;
          }
          .route-nav a {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            padding: 8px 14px;
            background: rgba(255,255,255,0.75);
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border-radius: 10px;
            text-decoration: none;
            font-size: 14px;
            font-weight: 500;
            color: #4f46e5;
            box-shadow: 0 2px 12px rgba(0,0,0,0.12);
            border: 1px solid rgba(255,255,255,0.3);
            transition: all 0.2s;
          }
          .route-nav a:hover { background: rgba(255,255,255,0.9); }
          @media (prefers-color-scheme: dark) {
            .route-nav a {
              background: rgba(15, 23, 42, 0.7);
              border-color: rgba(255,255,255,0.08);
              color: #818cf8;
              box-shadow: 0 2px 12px rgba(0,0,0,0.4);
            }
            .route-nav a:hover { background: rgba(15, 23, 42, 0.85); }
          }
        </style>
      </head>
      <body>
        <div class="route-nav">
          <a href="/">← 返回</a>
        </div>
        <div class="route-panel" id="route-panel">
          <input type="date" id="route-date" />
          <span class="route-status" id="route-status"></span>
          <span class="route-info">
            <span id="route-count"></span>
            <span id="route-range"></span>
          </span>
        </div>
        <div id="route-map" data-endpoint="/api/locations"></div>
        <script src="/vendor/leaflet.js"></script>
        <script>
          const mapEl = document.getElementById('route-map');
          const dateInput = document.getElementById('route-date');
          const statusEl = document.getElementById('route-status');
          const countEl = document.getElementById('route-count');
          const rangeEl = document.getElementById('route-range');
          const endpoint = mapEl.dataset.endpoint || '';
          let map, trackLayer, startMarker, endMarker;

          /* 使用东八区时间计算今天日期 */
          const now = new Date();
          const utc = now.getTime() + now.getTimezoneOffset() * 60000;
          const cn = new Date(utc + 8 * 3600000);
          const localDate = cn.getFullYear() + '-' +
            String(cn.getMonth() + 1).padStart(2, '0') + '-' +
            String(cn.getDate()).padStart(2, '0');

          const params = new URLSearchParams(window.location.search);
          const initialDate = params.get('date') || localDate;
          dateInput.value = initialDate;

          function setStatus(text, tone) {
            statusEl.textContent = text || '';
            statusEl.dataset.tone = tone || '';
          }

          /* 将 UTC 时间戳转为东八区时间显示 */
          function formatTimeCN(value) {
            if (!value) return '';
            const d = new Date(value);
            if (Number.isNaN(d.getTime())) return '';
            const cn = new Date(d.getTime() + (d.getTimezoneOffset() + 480) * 60000);
            const pad = n => String(n).padStart(2, '0');
            return pad(cn.getHours()) + ':' + pad(cn.getMinutes()) + ':' + pad(cn.getSeconds());
          }

          function normalizePoints(data) {
            if (Array.isArray(data)) return data;
            if (data && Array.isArray(data.points)) return data.points;
            return [];
          }

          function toLatLng(p) {
            const lat = Number(p.lat ?? p.latitude);
            const lng = Number(p.lng ?? p.lon ?? p.longitude);
            if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
            return [lat, lng];
          }

          function ensureMap(center) {
            if (!map) {
              map = L.map('route-map', {
                preferCanvas: true,
                zoomControl: false
              });
              L.control.zoom({ position: 'bottomright' }).addTo(map);
              L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OSM</a>'
              }).addTo(map);
              L.control.scale({ position: 'bottomleft' }).addTo(map);
            }
            map.setView(center, 12);
          }

          function renderTrack(points) {
            const latlngs = points.map(toLatLng).filter(Boolean);
            if (latlngs.length === 0) {
              setStatus('无数据', 'empty');
              countEl.textContent = '';
              rangeEl.textContent = '';
              return;
            }

            ensureMap(latlngs[0]);
            if (trackLayer) map.removeLayer(trackLayer);
            if (startMarker) map.removeLayer(startMarker);
            if (endMarker) map.removeLayer(endMarker);

            trackLayer = L.polyline(latlngs, {
              color: '#6366f1', weight: 3.5, opacity: 0.85,
              smoothFactor: 1.2, lineJoin: 'round'
            }).addTo(map);
            map.fitBounds(trackLayer.getBounds(), { padding: [40, 40] });

            startMarker = L.circleMarker(latlngs[0], {
              radius: 6, color: '#fff', fillColor: '#10b981',
              fillOpacity: 1, weight: 2
            }).addTo(map).bindTooltip('起点');

            endMarker = L.circleMarker(latlngs[latlngs.length - 1], {
              radius: 6, color: '#fff', fillColor: '#ef4444',
              fillOpacity: 1, weight: 2
            }).addTo(map).bindTooltip('终点');

            countEl.textContent = latlngs.length + ' 点';
            const st = formatTimeCN(points[0]?.ts || points[0]?.time || points[0]?.timestamp);
            const et = formatTimeCN(points[points.length - 1]?.ts || points[points.length - 1]?.time || points[points.length - 1]?.timestamp);
            rangeEl.textContent = st && et ? st + ' ~ ' + et : '';
            setStatus('✓', 'success');
          }

          async function loadDate(date) {
            if (!date || !endpoint) return;
            setStatus('加载中…', 'loading');
            countEl.textContent = '';
            rangeEl.textContent = '';
            try {
              const res = await fetch(endpoint + '?date=' + date);
              if (!res.ok) throw new Error(res.status);
              const data = await res.json();
              renderTrack(normalizePoints(data));
            } catch (e) {
              setStatus('失败', 'error');
            }
          }

          dateInput.addEventListener('change', function() {
            const date = dateInput.value;
            const url = new URL(window.location.href);
            url.searchParams.set('date', date);
            window.history.replaceState({}, '', url.toString());
            loadDate(date);
          });

          if (endpoint) loadDate(initialDate);
          else setStatus('未配置', 'error');
        </script>
      </body>
    </html>
    """
  end

  def page(assigns) do
    ~H"""
    <.layout
      title={"#{@title} — #{Content.site_title()}"}
      route={@route}
    >
      <div class="mb-8 pb-6 border-b border-gray-200 dark:border-gray-800">
        <h1 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100"><%= @title %></h1>
      </div>
      
      <article class="prose prose-zinc dark:prose-invert max-w-none">
        <%= raw @body %>
      </article>
      
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500 dark:text-gray-400">
        <p id="footer-cr"></p>
      </footer>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          let currentYear = new Date().getFullYear();
          let footerYear = document.getElementById('footer-cr');
          let wlink = '<a href="https://www.wongcw.cn" target="_blank" class="hover:text-indigo-500 transition">wangcw</a>';
          let elink = '<a href="https://erlang.org" target="_blank" class="hover:text-indigo-500 transition">Elixir/OTP</a>';
          let vlink = '<a href="https://vercel.com" target="_blank" class="hover:text-indigo-500 transition">Vercel</a>';
          footerYear.innerHTML = "Generated by " + elink + " & Published on " + vlink + "<br>Copyright © " + wlink + " 2020-" + currentYear + " All Rights Reserved";
        });
      </script>
    </.layout>
    """
  end

  def layout(assigns) do
    ~H"""
    <!DOCTYPE html>
    <html lang="zh-CN" class="scroll-smooth">
      <head>
        <meta charset="utf-8" />
        <title><%= @title %></title>
        <meta name="author" content={Content.site_author()} />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="ROBOTS" content="INDEX, FOLLOW" />
        <meta property="og:title" content={@title} />
        <meta property="og:url" content={"#{Content.site_url()}#{@route}"}>
        <meta name="color-scheme" content="light dark" />
        <link rel="stylesheet" href="/assets/app.css" />
      </head>
      <body class="bg-gray-50 text-gray-900 dark:bg-[#0f172a] dark:text-gray-100 min-h-screen antialiased flex flex-col">
        <header class="sticky top-0 z-50 w-full backdrop-blur transition-colors duration-500 bg-white/75 dark:bg-[#0f172a]/75 border-b border-gray-200 dark:border-gray-800">
          <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
              <div class="flex-shrink-0">
                <a href="/" class="font-bold text-xl tracking-tight text-indigo-600 dark:text-indigo-400 font-serif italic">wangcw</a>
              </div>
              <nav class="flex space-x-6 text-sm font-medium text-gray-700 dark:text-gray-300">
                <a href="/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">主页</a>
                <a href="/archive/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">归档</a>
                <a href="/routes/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">轨迹</a>
                <a href="/about/" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition">关于</a>
              </nav>
            </div>
          </div>
        </header>
        <main class="flex-grow max-w-3xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <%= render_slot(@inner_block) %>
        </main>
      </body>
    </html>
    """
  end

  def redirect(assigns) do
    ~H"""
    <!DOCTYPE html>
    <html lang="en-us">
      <head>
        <title><%= @target%></title>
        <link rel="canonical" href={@target}>
        <meta name="robots" content="noindex">
        <meta charset="utf-8">
        <meta http-equiv="refresh" content={"0; url=#{@target}"}>
      </head>
    </html>
    """
  end
end
